version: '3.8'

services:
  frontend:
    image: phonebook-frontend-dev
    build:
      context: ./phonebook-frontend/
      dockerfile: dev.Dockerfile
    volumes:
      - ./phonebook-frontend/:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      - WDS_SOCKET_HOST=127.0.0.1 
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true 
    ports:
      - 3000:3000
    container_name: phonebook-front-dev

  backend:                   
    image: phonebook-backend-dev 
    build:
      context: ./phonebook-backend
      dockerfile: dev.Dockerfile 
    volumes:
      - ./phonebook-backend:/usr/src/app
      - /usr/src/app/node_modules           
    ports:            
      - 3001:3001
    container_name: phonebook-back-dev